basic: &BASIC
  checkpoint_dir: checkpoints/
  lr: 0.001
  batch_size: 256
  l1_lambda: 1e-05
  l2_lambda: 0.0001
  n_tasks: 10
  task_to_forget: [6]
  steps_to_forget: 25
  importance_criteria: first_Taylor_approximation
  need_coreset: True
  online_importance: False
  num_gpus_total: 4
  num_gpus_to_use: 1
  coreset_size: 1000
  use_cges: False
  use_set_based_mask: False
  layerwise_pruning: True
  retrain_task_iter: 80
  policies_for_expr: ["RANDOM", "MEAN", "MAX", "MEAN+DEV", "MAX+DEV"]

SFDEN_FORGET: &SFDEN_FORGET
  <<: *BASIC
  max_iter: 1200
  gl_lambda: 0.001
  regular_lambda: 0.5
  ex_k: 10
  loss_thr: 0.01
  spl_thr: 0.05
  need_coreset: True
  layerwise_pruning: False
  policies_for_expr: ["RANDOM", "MEAN", "MAX", "MEAN+DEV"]
  expr_type: FORGET
  model: SFDEN
  support_model: ["SMALL_FC_MNIST"]

SFDEN_MULTIPLE_FORGET:
  <<: *SFDEN_FORGET
  task_to_forget_list: [[], [1, 2], [1, 2, 3, 4], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6, 7, 8]]
  mixing_coeff_list: [0.0, 0.9995, 0.999499999740638, 0.9995, 0.9995]
  tau_list: [0.0, 0.009994998511779693, 0.009994995715065756, 0.009088542765656765, 0.004224613571725346]
  expr_type: MULTIPLE_FORGET

SFDEN_RETRAIN:
  <<: *SFDEN_FORGET
  retrain_task_iter: 8
  steps_to_forget: 10
  expr_type: RETRAIN

SFEWC_FORGET: &SFEWC_FORGET
  <<: *BASIC
  max_iter: 20
  l1_lambda: 0.0
  l2_lambda: 0.0005
  ewc_lambda: 0.4
  need_coreset: True
  layerwise_pruning: False
  online_importance: False
  policies_for_expr: ["RANDOM", "MEAN", "MAX", "MEAN+DEV"]
  expr_type: FORGET
  model: SFEWC
  support_model: ["XLARGE_FC_MNIST"]

SFEWC_MULTIPLE_FORGET:
  <<: *SFEWC_FORGET
  task_to_forget_list: [[], [1, 2], [1, 2, 3, 4], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6, 7, 8]]
  mixing_coeff_list: [0.0, 0.9995, 0.9994999800345135, 0.9995, 0.2118713370557824]
  tau_list: [0.0, 0.0019621552206627473, 0.0031022630644842873, 0.0021440668246421853, 0.0026038630416280167]
  expr_type: MULTIPLE_FORGET

SFEWC_RETRAIN:
  <<: *SFEWC_FORGET
  retrain_task_iter: 70
  steps_to_forget: 22
  expr_type: RETRAIN

SFHPS_FORGET: &SFHPS_FORGET
  <<: *BASIC
  batch_size: 1000
  max_iter: 100
  l1_lambda: 1e-04
  l2_lambda: 0.0
  need_coreset: False
  layerwise_pruning: False
  expr_type: FORGET
  model: SFHPS
  support_model: ["LARGE_FC_MNIST"]

SFHPS_MASK:
  <<: *SFHPS_FORGET
  use_set_based_mask: True
  mask_type: ADAPTIVE
  mask_alpha: 1.5
  mask_not_alpha: -2.0
  expr_type: MASK

SFLCL10_FORGET: &SFLCL10_FORGET
  <<: *BASIC
  max_iter: 1350
  l1_lambda: 0.0
  l2_lambda: 2e-06
  need_coreset: False
  expr_type: FORGET
  model: SFLCL
  support_model: ["SMALL_CONV_MNIST", "ALEXNETV_MNIST", "ALEXNETV_CIFAR10"]
  policies_for_expr: ["RANDOM", "MEAN", "MAX", "MEAN+DEV", "MAX+DEV"]

SFLCL10_MASK: &SFLCL10_MASK
  <<: *SFLCL10_FORGET
  max_iter: 3500
  l1_lambda: 2e-06
  l2_lambda: 0.0
  use_set_based_mask: True
  mask_type: ADAPTIVE
  mask_alpha: 2.0
  mask_not_alpha: [-5.4, -5.6, -6.4, -4.4]
  expr_type: MASK
  policies_for_expr: ["RANDOM", "MEAN", "MAX", "MAX+DEV"]

SFLCL10_MASK_MULTIPLE_FORGET:
  <<: *SFLCL10_MASK
  task_to_forget_list: [[], [4, 8], [4, 8, 10, 7], [4, 8, 10, 7, 6, 2], [4, 8, 10, 7, 6, 2, 1, 3]]
  mixing_coeff_list: [0.0, 0.0005, 0.7472940343223929, 0.9995, 0.9995]
  tau_list: [0.0, 5.000075764705174e-06, 0.001659656838129292, 0.004664757789530214, 0.002906352815157769]
  expr_type: MULTIPLE_FORGET

SFLCL10_FORGET_MULTIPLE_FORGET:
  <<: *SFLCL10_FORGET
  task_to_forget_list: [[], [4, 8], [4, 8, 10, 7], [4, 8, 10, 7, 6, 2], [4, 8, 10, 7, 6, 2, 1, 3]]
  mixing_coeff_list: [0.0, 0.0005, 0.8387787064489711, 0.0005000070904050341, 0.47018133380827015]
  tau_list: [0.0, 5.000054211623081e-06, 5e-06, 5.000070904050341e-06, 0.0017644220568948424]
  expr_type: MULTIPLE_FORGET

SFLCL10_RETRAIN:
  <<: *SFLCL10_MASK
  retrain_task_iter: 2000
  steps_to_forget: 16
  expr_type: RETRAIN
