basic: &BASIC
  checkpoint_dir: checkpoints/
  lr: 0.001
  batch_size: 256
  l1_lambda: 1e-05
  l2_lambda: 0.0001
  n_tasks: 10
  task_to_forget: [6]
  steps_to_forget: 25
  importance_criteria: first_Taylor_approximation
  need_coreset: True
  online_importance: False
  gpu_num_list: [3]
  coreset_size: 1000
  use_cges: False
  use_set_based_mask: False

SFDEN_FORGET: &SFDEN_FORGET
  <<: *BASIC
  max_iter: 600
  gl_lambda: 0.001
  regular_lambda: 0.5
  ex_k: 10
  loss_thr: 0.1
  spl_thr: 0.1
  retrain_task_iter: 80
  retrain_max_iter_per_task: 150
  expr_type: FORGET
  model: SFDEN
  support_model: ["SMALL_FC_MNIST"]

SFDEN_RETRAIN:
  <<: *SFDEN_FORGET
  steps_to_forget: 15
  need_coreset: True
  expr_type: RETRAIN
  model: SFDEN
  support_model: ["SMALL_FC_MNIST"]

SFEWC_FORGET:
  <<: *BASIC
  max_iter: 20
  l1_lambda: 0.0
  l2_lambda: 0.0005
  ewc_lambda: 0.4
  retrain_task_iter: 80
  retrain_max_iter_per_task: 150
  need_coreset: True
  online_importance: False
  expr_type: FORGET
  model: SFEWC
  support_model: ["XLARGE_FC_MNIST"]

SFHPS_FORGET:
  <<: *BASIC
  batch_size: 1000
  max_iter: 40
  l1_lambda: 1e-04
  l2_lambda: 0.0
  need_coreset: False
  expr_type: FORGET
  model: SFHPS
  support_model: ["LARGE_FC_MNIST"]

SFHPS_MASK:
  <<: *BASIC
  batch_size: 1000
  max_iter: 40
  l1_lambda: 1e-04
  l2_lambda: 0.0
  need_coreset: False
  use_set_based_mask: True
  mask_type: ADAPTIVE
  mask_alpha: 6.0
  mask_not_alpha: -6.0
  expr_type: FORGET
  model: SFHPS
  support_model: ["NOT_XLARGE_FC_MNIST"]

SFLCL10_FORGET:
  <<: *BASIC
  max_iter: 200
  l1_lambda: 1e-06
  l2_lambda: 0.0
  need_coreset: False
  expr_type: FORGET
  model: SFLCL
  support_model: ["SMALL_CONV_MNIST", "ALEXNETV_MNIST", "ALEXNETV_CIFAR10"]

SFLCL10_MASK:
  <<: *BASIC
  max_iter: 200
  l1_lambda: 1e-06
  l2_lambda: 0.0
  need_coreset: False
  use_set_based_mask: True
  mask_type: ADAPTIVE
  mask_alpha: 15.0
  mask_not_alpha: -4.0
  expr_type: FORGET
  model: SFLCL
  support_model: ["SMALL_CONV_MNIST", "ALEXNETV_MNIST", "ALEXNETV_CIFAR10"]
